### ISSUE TITLE
fibers@3.1.1

### ISSUE THREAD

**Issue by vsathish07** [vsathish07/jenkins#1]
-bash-4.1$ npm install;npm test

> fibers@3.1.1 install /var/jenkins/workspace/Sathish-Test/Mocha/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/usr/local/node-v6.10.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/ins
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestError (/usr/local/node-v6.10.3-linux-x64/lib/node_modules/npm/node_modules/request/reque
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:309:9)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at TLSSocket.emit (events.js:188:7)
gyp ERR! stack     at connectErrorNT (net.js:1021:8)
gyp ERR! System Linux 2.6.32-754.14.2.el6.x86_64
gyp ERR! command "/usr/local/node-v6.10.3-linux-x64/bin/node" "/usr/local/node-v6.10.3-linux-x64/lib/node_modules/npm/node_modu
gyp ERR! cwd /var/jenkins/workspace/Sathish-Test/Mocha/node_modules/fibers
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.3 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (cur
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (cur
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none was installed.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN webdriverio-test@1.0.0 No repository field.
npm ERR! Linux 2.6.32-754.14.2.el6.x86_64
npm ERR! argv "/usr/local/node-v6.10.3-linux-x64/bin/node" "/usr/local/node-v6.10.3-linux-x64/lib/node_modules/npm/cli.js" "ins
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@3.1.1 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@3.1.1 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/jenkins/workspace/Sathish-Test/Mocha/npm-debug.log

> webdriverio-test@1.0.0 test /var/jenkins/workspace/Sathish-Test/Mocha
> http_proxy='' && rimraf ./test/reports/allure-results && rimraf ./test/reports/errorShots && wdio

**** let's go ****
[16:30:03]  COMMAND     POST     "/wd/hub/session"
[16:30:03]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for thi
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome.68_0.osx10_12
Error: Couldn't connect to selenium server
    at init() - runner.js:235:55
**** that's it ****
npm ERR! Test failed.  See above for more details.

**Comment by vsathish07** [comment]
could not install fibers@3.1.1, let me know how to resolve this issue
